name: Integration
on:
  pull_request:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python3 train.py

      - name: Write CML report
        run: |
          cat metrics.txt >> report.md
          cml comment create report.md

      - name: Output metrics
        run: cat metrics.txt